Add new action create-branch Use fedpkg instead of rhpkg Add better help and error messages

diff --git a/centpkg-sclo b/centpkg-sclo
--- a/centpkg-sclo
+++ b/centpkg-sclo
@@ -1,19 +1,23 @@
 #!/bin/bash
 
-# This is a wrapper script around rhpkg and cbs utility, that is especially
+# This is a wrapper script around fedpkg and cbs utility, that is especially
 # designed for working with packages and repos in SCLo SIG group.
-# The API should be the same as for centpkg, but currently uses RH internal
+#
+# The API should be the same as for centpkg, but currently uses Fedora's
 # look-aside cache for storing binary files and github repos under
 # sclorg-distgit organization.
+#
 # The branches we use for dist-git (on github) are following this regexp:
 #
 #   r'sig-(?P<signame>\w+)(?P<centosversion>\d)-?(?P<projectname>\w+)?-?(?P<releasename>\w+)?'
-# (https://wiki.centos.org/BrianStinson/GitBranchesandKojiTags)
+# (based on https://wiki.centos.org/BrianStinson/GitBranchesandKojiTags)
 #
 # while:
 #   <projectname> is SCL name (including prefix sclo-, rh- if there is one in SCL name
-#   <releasename> is the namespace where the SCL is part of (rh for collections
-#                 that are rebuild of RHSCL or sclo for other SCLs)
+#   <releasename> is the namespace where the SCL is part of ('rh' for collections
+#                 that are rebuild of RHSCL or 'sclo' for other SCLs)
+
+GITHUB_ORG=https://github.com/sclorg-distgit
 
 get_branch_info() {
   # parsing branch name, we can get scl name, namespace and EL version
@@ -21,7 +25,8 @@ get_branch_info() {
   export branch=$(git rev-parse --abbrev-ref HEAD)
 
   if ! echo "${branch}" | grep -e '^sig-sclo\([0-9]*\)-\(.*\)-\([a-z]*\)$' &>/dev/null ; then
-    echo "Branch could not be parsed properly."
+    echo "Error: Branch could not be parsed properly."
+    echo
     usage
   fi
 
@@ -31,8 +36,8 @@ get_branch_info() {
 }
 
 srpm() {
-  rhpkg sources
-  rpmbuild -bs --nodeps --define "_sourcedir ." --define "_srcrpmdir ." --define "dist .el${el_ver}" -D "scl ${scl}" `rhpkg gimmespec`
+  fedpkg sources
+  rpmbuild -bs --nodeps --define "_sourcedir ." --define "_srcrpmdir ." --define "dist .el${el_ver}" -D "scl ${scl}" `fedpkg gimmespec`
 }
 
 get_srpm() {
@@ -54,17 +59,58 @@ build() {
 
 clone() {
   if [ -z "${1}" ] ; then
+    echo "Error: No argument given to clone. Please, specify component name without SCL prefix."
+    echo
     usage
   fi
-  git clone "https://github.com/sclorg-distgit/${1}.git"
+
+  git clone "${GITHUB_ORG}/${1}.git"
+
+  retval=$?
+  if [ $retval -ne 0 ] ; then
+    echo "Error: 'git clone' call failed, it may be because requested repository is not created yet."
+    echo "Create the repository first at ${GITHUB_ORG}."
+    exit $retval
+  fi
 }
 
 prep() {
-  rhpkg --dist "rhel-${el_ver}" prep
+  fedpkg --dist "rhel-${el_ver}" prep
+}
+
+branch_exists() {
+  if [ -z "${1}" ] ; then
+    echo "You must set branch name as parameter of branch_exists"
+    exit 1
+  fi
+  [ -n "$(git branch --list ${1})" ] && return 0 || return 1
+}
+
+create_branch() {
+  if [ -z "${2}" ] ; then
+    echo "Error: action create-branch requires two parameters: <scl-name> <centos-version> [ <namespace> ]"
+    echo "<scl-name>        Name of the collection this component is prepared for"
+    echo "<centos-version>  Version '6', '7', ..."
+    echo "<namespace>       Namespace 'rh' or 'sclo', rh is used if not specified"
+    echo
+    usage
+  fi
+  scl=${1}
+  el_ver=${2}
+  namespace=${3-rh}
+  branch="sig-sclo${el_ver}-${scl}-${namespace}"
+  branch_exists "${branch}" && echo "Branch ${branch} already exists." && return
+  git checkout -b "${branch}"
 }
 
 usage() {
-  echo "Usage `basename $0` {build,clone,commit,local,prep,pull,scratch-build,srpm}"
+  echo "Usage `basename $0` {build,clone,commit,create-branch,import,local,prep,pull,scratch-build,srpm}"
+  echo
+  echo "Actions except create-branch work the same as we know it from fedpkg."
+  echo "Action create-branch creates a new branch in current repository."
+  echo "For creating entirely new repository, go to ${GITHUB_ORG}."
+  echo
+  echo "Example workflow is available in https://github.com/sclorg/centpkg-sclo/blob/master/README.md."
   exit 1
 }
 
@@ -77,7 +123,7 @@ shift
 
 # some actions don't need to have branch to be properly parsed
 case "${action}" in
-  clone|switch-branch) ;;
+  clone|switch-branch|create-branch) ;;
   *) get_branch_info ;;
 esac
 
@@ -87,7 +133,8 @@ case "${action}" in
   build) build $@ ;;
   prep) prep $@ ;;
   scratch-build) scratch_build $@ ;;
-  local|pull|commit|switch-branch) rhpkg ${action} $@ ;;
+  create-branch) create_branch $@ ;;
+  local|pull|commit|switch-branch|import) fedpkg ${action} $@ ;;
   *) usage ;;
 esac
 
